/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticket_booking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appInstantiates() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
